### PR TITLE
Update gemspec and drop support of old ruby\rack versions

### PR DESCRIPTION
**Pull request by antonpaisov**
- When installing talkable-ruby from rubygems, the conditionals in gemspec
weren't working correct. Given that the conditions were there for the
sake of support of ruby versions that are no longer supported by the
ruby team itself, I've decided to drop that support too.

- Cleaned up and reordered some of the spec fields

- Updated readme accordingly

### CODE REVIEW

**Comment by zhuravel** [comment]
Please also update `solano.yml`: `bundler_version` and `ruby_version`.

**Comment by antonpaisov** [comment]
@zhuravel done

**Comment by antonpaisov** [comment]
@zhuravel if it's all good, I'd like to push a 1.0.1 version to rubygems after we merge it. How do I do that? How has the rubygems credentials and who should approve the push?

**Review by zhuravel — APPROVED** [review]
LGTM. Please ask @vitalikdanchenko to help you with gem push.

**Pull request merged**
